language = "Common Lisp"
version = "2.2.7"
compiled = false
extension = "cl"
build_command = []
environment = [ "SBCL_HOME=/opt/sbcl/2.2.7/lib/sbcl", "PATH=/opt/sbcl/2.2.7:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" ]
run_command = [ "/opt/sbcl/2.2.7/bin/sbcl", "--script", "{file}" ]
test_file = "test.cl"
aliases = ["clisp", "sbcl"]
should_limit_memory = true
memory_limit = 2048
process_limit = 2048
allowed_entrypoints = 1
