language = ".NET"
version = "6.0.300"
compiled = true
extension = "cs"
environment = [ "DOTNET_ROOT=/opt/dotnet/6.0.300", "PATH=/opt/dotnet/6.0.300" ]
build_command = [
  """bash -c 'cat <<EOF > Application.csproj
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

</Project>
EOF'""",
  "&&",
  "/opt/dotnet/6.0.300/dotnet",
  "build",
  "--nologo",
  "--configuration",
  "Release"
]
run_command = [ "/opt/dotnet/6.0.300/dotnet", "run", "--no-build", "--configuration", "Release" ]
test_file = "test.cs"
aliases = ["dotnet", "c#", "csharp"]
should_limit_memory = true
memory_limit = 256
process_limit = 1024
allowed_entrypoints = 1
