language = "Tengo"
version = "2.16.1"
compiled = false
extension = "tengo"
environment = [ "PATH=/opt/tengo/2.16.1" ]
build_command = []
run_command = [ "tengo", "{file}" ]
aliases = [ "tengo", "tgo", "tg" ]
test_file = "test.tengo"
should_limit_memory = true
memory_limit = 256
process_limit = 256
allowed_entrypoints = 1
