language = "PHP"
version = "8.1"
compiled = false
extension = "php"
environment = []
build_command = []
run_command = [ "php", "{file}" ]
test_file = "test.php"
aliases = ["php"]
should_limit_memory = true
memory_limit = 512
process_limit = 256
allowed_entrypoints = 1
