language = "Janet"
version = "1.27.0"
compiled = false
extension = "janet"
build_command = []
run_command = [ "janet", "{file}" ]
environment = [ "PATH=/opt/janet/v1.27.0/bin" ]
test_file = "test.janet"
aliases = ["janet"]
should_limit_memory = true
memory_limit = 512
process_limit = 512
allowed_entrypoints = 1
