// @generated by protobuf-ts 2.2.2 with parameter server_none,client_grpc1,generate_dependencies,optimize_code_size,add_pb_suffix
// @generated from protobuf file "logger.proto" (package "logger", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message logger.EmptyResponse
 */
export interface EmptyResponse {
}
/**
 * @generated from protobuf message logger.EmptyRequest
 */
export interface EmptyRequest {
}
/**
 * @generated from protobuf message logger.LogData
 */
export interface LogData {
    /**
     * @generated from protobuf field: string request_id = 1;
     */
    requestId: string;
    /**
     * @generated from protobuf field: string application = 2;
     */
    application: string;
    /**
     * @generated from protobuf field: string message = 3;
     */
    message: string;
    /**
     * @generated from protobuf field: optional logger.Level level = 4;
     */
    level?: Level;
    /**
     * @generated from protobuf field: optional logger.Environment environment = 5;
     */
    environment?: Environment;
    /**
     * @generated from protobuf field: optional string language = 6;
     */
    language?: string;
    /**
     * @generated from protobuf field: map<string, string> body = 7;
     */
    body: {
        [key: string]: string;
    };
    /**
     * timestamp follows unix millisecond timestamp
     *
     * @generated from protobuf field: optional int64 timestamp = 8;
     */
    timestamp?: bigint;
}
/**
 * @generated from protobuf message logger.LogRequest
 */
export interface LogRequest {
    /**
     * @generated from protobuf field: string access_token = 1;
     */
    accessToken: string;
    /**
     * @generated from protobuf field: logger.LogData data = 2;
     */
    data?: LogData;
}
/**
 * @generated from protobuf message logger.Healthcheck
 */
export interface Healthcheck {
    /**
     * @generated from protobuf field: string status = 1;
     */
    status: string;
}
/**
 * @generated from protobuf message logger.ReadLogRequest
 */
export interface ReadLogRequest {
    /**
     * @generated from protobuf field: optional logger.Level level = 1;
     */
    level?: Level;
    /**
     * @generated from protobuf field: optional string request_id = 2;
     */
    requestId?: string;
    /**
     * @generated from protobuf field: optional string application = 3;
     */
    application?: string;
    /**
     * timestamp_from is in unix millisecond format
     *
     * @generated from protobuf field: optional int64 timestamp_from = 4;
     */
    timestampFrom?: bigint;
    /**
     * timestamp_to is in unix millisecond format
     *
     * @generated from protobuf field: optional int64 timestamp_to = 5;
     */
    timestampTo?: bigint;
}
/**
 * @generated from protobuf message logger.ReadLogResponse
 */
export interface ReadLogResponse {
    /**
     * @generated from protobuf field: repeated logger.LogData data = 1;
     */
    data: LogData[];
}
/**
 * @generated from protobuf enum logger.Level
 */
export enum Level {
    /**
     * @generated from protobuf enum value: DEBUG = 0;
     */
    DEBUG = 0,
    /**
     * @generated from protobuf enum value: INFO = 1;
     */
    INFO = 1,
    /**
     * @generated from protobuf enum value: WARNING = 2;
     */
    WARNING = 2,
    /**
     * @generated from protobuf enum value: ERROR = 3;
     */
    ERROR = 3,
    /**
     * @generated from protobuf enum value: CRITICAL = 4;
     */
    CRITICAL = 4
}
/**
 * @generated from protobuf enum logger.Environment
 */
export enum Environment {
    /**
     * @generated from protobuf enum value: UNSET = 0;
     */
    UNSET = 0,
    /**
     * @generated from protobuf enum value: DEVELOPMENT = 1;
     */
    DEVELOPMENT = 1,
    /**
     * @generated from protobuf enum value: TESTING = 2;
     */
    TESTING = 2,
    /**
     * @generated from protobuf enum value: STAGING = 3;
     */
    STAGING = 3,
    /**
     * @generated from protobuf enum value: PRODUCTION = 4;
     */
    PRODUCTION = 4
}
// @generated message type with reflection information, may provide speed optimized methods
class EmptyResponse$Type extends MessageType<EmptyResponse> {
    constructor() {
        super("logger.EmptyResponse", []);
    }
}
/**
 * @generated MessageType for protobuf message logger.EmptyResponse
 */
export const EmptyResponse = new EmptyResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class EmptyRequest$Type extends MessageType<EmptyRequest> {
    constructor() {
        super("logger.EmptyRequest", []);
    }
}
/**
 * @generated MessageType for protobuf message logger.EmptyRequest
 */
export const EmptyRequest = new EmptyRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class LogData$Type extends MessageType<LogData> {
    constructor() {
        super("logger.LogData", [
            { no: 1, name: "request_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "application", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "level", kind: "enum", opt: true, T: () => ["logger.Level", Level] },
            { no: 5, name: "environment", kind: "enum", opt: true, T: () => ["logger.Environment", Environment] },
            { no: 6, name: "language", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "body", kind: "map", K: 9 /*ScalarType.STRING*/, V: { kind: "scalar", T: 9 /*ScalarType.STRING*/ } },
            { no: 8, name: "timestamp", kind: "scalar", opt: true, T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message logger.LogData
 */
export const LogData = new LogData$Type();
// @generated message type with reflection information, may provide speed optimized methods
class LogRequest$Type extends MessageType<LogRequest> {
    constructor() {
        super("logger.LogRequest", [
            { no: 1, name: "access_token", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "data", kind: "message", T: () => LogData }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message logger.LogRequest
 */
export const LogRequest = new LogRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Healthcheck$Type extends MessageType<Healthcheck> {
    constructor() {
        super("logger.Healthcheck", [
            { no: 1, name: "status", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message logger.Healthcheck
 */
export const Healthcheck = new Healthcheck$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ReadLogRequest$Type extends MessageType<ReadLogRequest> {
    constructor() {
        super("logger.ReadLogRequest", [
            { no: 1, name: "level", kind: "enum", opt: true, T: () => ["logger.Level", Level] },
            { no: 2, name: "request_id", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "application", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "timestamp_from", kind: "scalar", opt: true, T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 5, name: "timestamp_to", kind: "scalar", opt: true, T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message logger.ReadLogRequest
 */
export const ReadLogRequest = new ReadLogRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ReadLogResponse$Type extends MessageType<ReadLogResponse> {
    constructor() {
        super("logger.ReadLogResponse", [
            { no: 1, name: "data", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => LogData }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message logger.ReadLogResponse
 */
export const ReadLogResponse = new ReadLogResponse$Type();
/**
 * @generated ServiceType for protobuf service logger.Logger
 */
export const Logger = new ServiceType("logger.Logger", [
    { name: "CreateLog", options: {}, I: LogRequest, O: EmptyResponse },
    { name: "ReadLog", options: {}, I: ReadLogRequest, O: ReadLogResponse },
    { name: "Ping", options: {}, I: EmptyRequest, O: Healthcheck }
]);
