language = "Erlang"
version = "25.1.2"
compiled = false
extension = "erl"
environment = [ "PATH=/opt/erlang/25/bin" ]
build_command = []
run_command = [ "escript", "{file}" ]
test_file = "test.erl"
aliases = ["erl", "erlang", "beam"]
should_limit_memory = true
memory_limit = 256
process_limit = 256
allowed_entrypoints = 1
