// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_500.tsx";
import * as $2 from "./routes/_app.tsx";
import * as $3 from "./routes/index.tsx";
import * as $$0 from "./islands/BackToTop.tsx";
import * as $$1 from "./islands/Form.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_500.tsx": $1,
    "./routes/_app.tsx": $2,
    "./routes/index.tsx": $3,
  },
  islands: {
    "./islands/BackToTop.tsx": $$0,
    "./islands/Form.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
