name: PR / Main Systems

on:
  pull_request:
    paths:
      - auth/**
      - landing/**
      - rce/**
      - registration/**

jobs:
  auth:
    name: Auth
    runs-on: ubuntu-latest
    container: golang:1.19
    timeout-minutes: 30
    defaults:
      run:
        working-directory: ./auth
    services:
      db:
        image: redis:7-bullseye
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified

      - name: Build test
        run: go build .

      - name: Run test
        run: go test -v -coverprofile=coverage.out -covermode=atomic ./...
        env:
          ENVIRONMENT: github-actions
          SENTRY_DSN: ""
          REDIS_URL: redis://@db:6379

      - name: Codecov
        uses: codecov/codecov-action@v3
  rce:
    name: RCE
    runs-on: ubuntu-latest
    container: node:16.14.0-bullseye
    timeout-minutes: 30
    defaults:
      run:
        working-directory: ./rce
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified

      - name: Setup packages && nosocket
        run: >
          apt-get update &&
          apt-get install -y coreutils binutils build-essential libseccomp-dev gcc apt-utils &&
          make -C ./nosocket/ all && make -C ./nosocket/ install

      - name: Setup directory
        run: mkdir -p /code/$(whoami)

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npx eslint --ext .ts,.js,.cjs .

      - name: Build
        run: npm run build

      - name: Test & coverage
        run: npm run test

      - name: Codecov
        uses: codecov/codecov-action@v3

  landing:
    name: Landing
    runs-on: ubuntu-latest
    container: node:18.6.0
    timeout-minutes: 30
    defaults:
      run:
        working-directory: ./landing
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Check formatting
        run: pnpm fmt:check

      - name: Build
        run: pnpm build

  registration:
    name: Registration
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:6.0
    timeout-minutes: 30
    defaults:
      run:
        working-directory: ./registration
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified

      - name: Restore
        run: dotnet restore "Registration.csproj"

      - name: Build
        run: dotnet build "Registration.csproj" --no-restore -c Release
