name: SDK

on:
  release:
    types:
      - published

jobs:
  js-publish:
    name: JavaScript Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: ./sdk/javascript
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts
      - run: npm install
      - run: npm run build
      - run: npm publish --access public --tag latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  dotnet-publish:
    name: .NET Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
        run:
          working-directory: ./sdk/dotnet
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.x"
      - name: Pack nugets
        run: dotnet pack Pesto -c Release --output .
      - name: Push to NuGet
        run: dotnet nuget push "*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json